config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#index'

  resources :static_pages
  resources :gossips do
    resources :comments
  end
  resources :users
  resources :cities
  resources :sessions, only: [:new, :create, :destroy]
  resources :likes, only: [:show, :new, :create, :destroy]

  get '/team', to: 'static_pages#team'
  get '/contact', to: 'static_pages#contact'
  get '/welcome/', to: 'static_pages#welcome'
  get '/welcome/:anything', to: 'static_pages#welcome'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
  has_many :gossips, through: :users

  validates :name,
  presence: true

  validates :zip_code,
  presence: true,
  uniqueness: true,
  format: { with: /\A(([0-8][0-9])|(9[0-5])|(2[ab]))[0-9]{3}\z/, message: "please enter a valid french zip code" }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :gossip

  validates :content,
  presence: true

  validates :user_id,
  presence: true

  validates :gossip_id,
  presence: true
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user
  has_many :tag_gossip_links
  has_many :tags, through: :tag_gossip_links
  has_many :comments
  has_many :likes

  validates :title,
  presence: true,
  length: { in: 1..25 }

  validates :content,
  presence: true

end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :gossip
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: "User"
  has_many :recipient_to_pm_links, foreign_key: 'received_message_id'
  has_many :recipients, foreign_key: 'recipient_id', class_name: "User", through: :recipient_to_pm_links
end

app/models/recipient_to_pm_link.rb
class RecipientToPmLink < ApplicationRecord
  belongs_to :recipient, class_name: "User"
  belongs_to :received_message, class_name: "PrivateMessage"
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :tag_gossip_links
  has_many :gossips, through: :tag_gossip_links

  validates :title,
  presence: true,
  uniqueness: true
end

app/models/tag_gossip_link.rb
class TagGossipLink < ApplicationRecord
  belongs_to :gossip
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord

  has_secure_password

  belongs_to :city
  has_many :gossips
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :recipient_to_pm_links, foreign_key: 'recipient_id'
  has_many :received_messages, foreign_key: 'received_message_id', class_name: "PrivateMessage", through: :recipient_to_pm_links
  has_many :likes
  
  validates :email,
  presence: true,
  uniqueness: true,
  format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "Mauvais format" }

  validates :password,
  presence: true,
  length: { in: 6..20 }

end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController

  def show
    @city = City.find(params[:id])
  end

end

app/controllers/gossips_controller.rb
class GossipsController < ApplicationController

  before_action :authenticate_user, only: [:show, :new, :create, :edit, :update, :destroy]
  before_action :currentuser_gossipauthor?, only: [:edit, :update, :destroy]

  def show
    @gossip = Gossip.find(params[:id])
  end

  def new
    @gossip = Gossip.new
  end

  def create
    @gossip = Gossip.new(title:params[:title], content:params[:content], user_id:current_user.id) # avec xxx qui sont les données obtenues à partir du formulaire

    if @gossip.save # essaie de sauvegarder en base @gossip
      redirect_to '/'
      flash[:success] = "Potin créé ! Merci d'entretenir le commérage 👌"
      # si ça marche, il redirige vers la page d'index du site
    else
      # sinon, il render la view new (qui est celle sur laquelle on est déjà)
      render 'new'
    end

  end

  def edit
    @gossip = Gossip.find(params[:id])
  end

  def update
    @gossip = Gossip.find(params[:id])

    if @gossip.update(gossip_params)
      redirect_to @gossip
    else
      render :edit
    end

  end

  def destroy
    @gossip = Gossip.find(params[:id])
    @gossip.destroy
    redirect_to root_path
  end

  private

  def gossip_params
    params.require(:gossip).permit(:title, :content)
  end

  def currentuser_gossipauthor?
    unless current_user.id == Gossip.find(params[:id]).user.id
      redirect_to root_path
      flash[:danger] = "Non non non ;)"
    end
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def show
  end

  def new
      @like = Like.new
  end

  def create
      @like = Like.create(user_id: current_user.id , gossip_id: params[:gossip_id])
      redirect_back(fallback_location: root_path)
  end

  def destroy
      @like = Like.find(params[:id])
      like_user = @like.user

      if current_user == like_user
          @like.destroy
          redirect_back(fallback_location: root_path)
      else
      end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @author = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(first_name:params[:first_name], last_name:params[:last_name], email:params[:email], password:params[:password], city_id:City.last.id) # avec xxx qui sont les données obtenues à partir du formulaire

    if @user.save # essaie de sauvegarder en base @gossip
      session[:user_id] = @user.id
      redirect_to root_path
      # si ça marche, il redirige vers la page d'index du site
    else
      # sinon, il render la view new (qui est celle sur laquelle on est déjà)
      render 'new'
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def current_user
    User.find_by(id: session[:user_id])
  end

   def log_in(user)
    session[:user_id] = user.id
  end

  def logged_in?
    if session[:user_id] !=nil
      return true
    else
      return false
    end
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cities/show.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Vive moi</title>
  </head>
  <body>

    <h1> Bienvenue dans la charmante ville de <b><%= @city.name %></b> </h1>

    <p>Voilà tous les potins du coin (tu ne verras plus jamais ton voisin du même oeil) :</p>

    <% @city.gossips.each do |gossip| %>
      <p>
        👉 <b><%= gossip.title %></b><br/>
        🙊 par <b><%= gossip.user.first_name %> <%= gossip.user.last_name %></b><br/>
      </p>

      <p>
        <%= link_to "Voir le potin", gossip_path(:id => gossip.id), class:"btn btn-primary btn-sm", role:"button" %>
        <%= link_to "Voir l'auteur", user_path(:id => gossip.user.id), class:"btn btn-primary btn-sm", role:"button" %>
          <% if gossip.likes.where(user_id: current_user.id).count > 0 %>
          <%= link_to "👎", like_path(:id=> gossip.likes.sample), class:"btn btn-danger btn-sm", role:"button", data: {:method => "delete"} %>
          <% else %>
          <%= link_to "👍", likes_path(:gossip_id=> gossip.id), class:"btn btn-info btn-sm", role:"button", data: {:method => "create"} %>
        <% end %>
        <span style="font-size:14px;">Likes :<%= gossip.likes.count %></span>
      </p>

    <% end %>

  </body>
</html>

app/views/gossips/author.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Vive moi</title>
  </head>
  <body>

    <h1>Author page</h1>

    <h1> Vous êtes sur la page de <%= @author.first_name %> </h1>

<p>Last name : <%= @author.last_name %> </p>
<p>Description : <%= @author.description %> </p>
<p>Email : <%= @author.email %> </p>
<p>Age : <%= @author.age %> </p>
<p>Ville : <%= @author.city_id %> </p>

  </body>
</html>

app/views/gossips/edit.html.erb
<html>
  <body>
    <!-- ... -->

    <%= form_for @gossip do |f| %>
      <div class="form-group">
        <label>Titre du gossip</label>
        <%= f.text_field :title, class: 'form-control' %>
      </div>
      <div class="form-group">
        <label>Contenu du gossip</label>
        <%= f.text_field :content, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.submit "Modifier le potin", class:"btn btn-primary" %>
      </div>
    <% end %>


    <!-- ... -->
  </body>
</html>

app/views/gossips/gossip.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Vive moi</title>
  </head>
  <body>

    <h1>Du potin, du potin, du potiiiin</h1>


    <h3><b> <%= @gossip.title %> </b></h3>
        <p> 👅 <%= @gossip.content %> </p>
        <p> 🗓 Date de création : <%= @gossip.created_at %> </p>
        <p> 💩 Ce doss' a été lâché par <%= @gossip.user.first_name %> (t'as cru qu'on allait garder ça anonyme)</p>
        <p> <%= link_to "Voir l'auteur", the_author_path(:id => @gossip.user.id), class:"btn btn-primary btn-sm", role:"button" %> </p>


  </body>
</html>

app/views/gossips/home.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Vive moi</title>
  </head>
    <style type="text/css">
   body {font-family: 'Nunito', sans-serif; text-align:center;}
   </style>

<body>

  <h1><b>Bienvenue dans l'endroit le plus approprié pour critiquer qui tu veux</b></h1>

  <p></p>
  <h3>Voilà les derniers potins :</h3>

  <% @all_gossips.each do |select| %>
      <p>
      👉 <b><%= select.title %></b><br/>
      🙊 par <b><%= select.user.first_name %></b><br/>
      <%= link_to "Voir le potin", the_gossip_path(:id => select.id), class:"btn btn-primary btn-sm", role:"button" %>
      </p>
      <% end %>


    <p></p>
    <a class="btn btn-warning" href="/gossips/new/" role="button">Crée un nouveau potin !</a>

  </body>
</html>

app/views/gossips/new.html.erb
<html>
  <body>
    <!-- ... -->

    <% if @gossip.errors.any? %>
      <div class="alert alert-danger" role="alert">
      <p> Nous n'avons pas réussi à créer le potin pour la (ou les) raison(s) suivante(s) :</p>
      <ul>
        <% @gossip.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
      </div>
    <% end %>

    <% if @gossip.save %>
      <div class="alert alert-success" role="alert">
      <p> Success!</p>
        </div>
        <% end %>

    <%= form_tag url_for(action: 'create'), method: "post" do %>

      <%= label_tag 'Titre' %>
      <%= text_field_tag 'title', @gossip.title %>
      <br /> <br />

      <%= label_tag 'Contenu' %>
      <%= text_area_tag 'content', @gossip.content %>
      <br /> <br />

      <%= submit_tag "Create Post" %>

    <% end %>


    <!-- ... -->
  </body>
</html>

app/views/gossips/show.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Vive moi</title>
  </head>
  <body>
    <% if flash[:danger] %>
  <div class="alert alert-danger" role="alert">
    <%= flash[:danger] %>
  </div>
<% end %>

    <h1>Du potin, du potin, du potiiiin</h1>

    <h3><b> <%= @gossip.title %> </b></h3>
        <p> 👅 <%= @gossip.content %> </p>
        <p> 🗓 Date de création : <%= @gossip.created_at %> </p>
        <p> 💩 Ce doss' a été lâché par <b><%= @gossip.user.first_name %> <%= @gossip.user.last_name %></b> (t'as cru qu'on allait garder ça anonyme)</p>
        <p>
          <% if logged_in? == true %>
            <% if @gossip.likes.where(user_id: current_user.id).count > 0 %>
            <%= link_to "👎", like_path(:id=> @gossip.likes.sample), class:"btn btn-danger btn-sm", role:"button", data: {:method => "delete"} %>
            <% else %>
            <%= link_to "👍", likes_path(:gossip_id=> @gossip.id), class:"btn btn-info btn-sm", role:"button", data: {:method => "create"} %>
          <% end %>
          <% end %>
          <span style="font-size:14px;">Likes :<%= @gossip.likes.count %></span>
        </p>
        <p>
        <%= link_to "Voir l'auteur", user_path(:id => @gossip.user.id), class:"btn btn-primary btn-sm", role:"button" %>
        <%= link_to "Voir la ville", city_path(:id => @gossip.user.city.id), class:"btn btn-primary btn-sm", role:"button" %>
        </p>
        <% if current_user.id == @gossip.user.id %>
        <p>
        <%= link_to "Modifier le potin", edit_gossip_path(:id => @gossip.id), class:"btn btn-warning btn-sm", role:"button" %>
        <%= link_to "Supprimer", @gossip, method: :delete, class:"btn btn-danger btn-sm", role:"button" %>
        </p>
        <% end %>

        <div class="formulaire">
        <p>
          <%= form_tag url_for(controller: :comments, action: :create, id: params[:id], gossip_id: params[:id]), method: "post" do %>
          <b><%= label_tag 'Continuer le commérage 👇' %></b> <br>
          <%= text_field_tag 'content'%>
          <%= submit_tag 'Commenter 😈', class:"btn btn-outline-dark btn-sm"%>
          <% end %>
        </p>
        </div>

        <p><b>Derniers commentaires</b></p>

        <% @gossip.comments.each do |comment| %>
          <p style="font-size:14px;"> <b><%= comment.user.first_name %></b> <br>
            <%= comment.content %> </p>
        <% end %>

  </body>
</html>

app/views/users/new.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Créer un compte</title>
  </head>
  <body>

    <% if @user.errors.any? %>
      <div class="alert alert-danger" role="alert">
      <p> Nous n'avons pas réussi à créer le compte pour la (ou les) raison(s) suivante(s) :</p>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
      </div>
    <% end %>

    <h1><b>Créer un compte</b></h1>

    <%= form_tag url_for(action: 'create'), method: "post" do %>
    <div class="form-group">
      <%= label_tag 'Prénom' %>
      <%= text_field_tag 'first_name', @user.first_name, class: 'form-control' %>
      <div class="form-group">
        <%= label_tag 'Nom' %>
        <%= text_field_tag 'last_name', @user.last_name, class: 'form-control' %>
      <div class="form-group">
        <%= label_tag 'Email*'%>
        <%= text_field_tag 'email', @user.email, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= label_tag 'Mot de passe*' %> <span style="font-size:12px;"> 6 à 20 caractères :)</span>
        <%= text_field_tag 'password', @user.password, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= submit_tag "Go", class:"btn btn-success" %>
      </div>
    <% end %>

  </body>
</html>

app/views/users/show.html.erb
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Vive moi</title>
  </head>
  <body>

    <h1> Haaave you met <b><%= @author.first_name %></b> ?</h1>

      <p>Last name : <%= @author.last_name %> </p>
      <p>Description : <%= @author.description %> </p>
      <p>Email : <%= @author.email %> </p>
      <p>Age : <%= @author.age %> ans</p>
      <p>Ville : <%= @author.city.name %> </p>

      <p>
        <%= link_to "Voir la ville", city_path(:id => @author.city.id), class:"btn btn-primary btn-sm", role:"button" %>
      </p>

  </body>
</html>