config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#index'

  resources :static_pages
  resources :gossips do
    resources :comments
  end
  resources :users
  resources :cities
  resources :sessions, only: [:new, :create, :destroy]
  resources :likes, only: [:show, :new, :create, :destroy]

  get '/team', to: 'static_pages#team'
  get '/contact', to: 'static_pages#contact'
  get '/welcome/', to: 'static_pages#welcome'
  get '/welcome/:anything', to: 'static_pages#welcome'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :users
  has_many :gossips, through: :users

  validates :name,
  presence: true

  validates :zip_code,
  presence: true,
  uniqueness: true,
  format: { with: /\A(([0-8][0-9])|(9[0-5])|(2[ab]))[0-9]{3}\z/, message: "please enter a valid french zip code" }
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :gossip

  validates :content,
  presence: true

  validates :user_id,
  presence: true

  validates :gossip_id,
  presence: true
end

app/models/gossip.rb
class Gossip < ApplicationRecord
  belongs_to :user
  has_many :tag_gossip_links
  has_many :tags, through: :tag_gossip_links
  has_many :comments
  has_many :likes

  validates :title,
  presence: true,
  length: { in: 1..25 }

  validates :content,
  presence: true

end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :gossip
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
  belongs_to :sender, class_name: "User"
  has_many :recipient_to_pm_links, foreign_key: 'received_message_id'
  has_many :recipients, foreign_key: 'recipient_id', class_name: "User", through: :recipient_to_pm_links
end

app/models/recipient_to_pm_link.rb
class RecipientToPmLink < ApplicationRecord
  belongs_to :recipient, class_name: "User"
  belongs_to :received_message, class_name: "PrivateMessage"
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :tag_gossip_links
  has_many :gossips, through: :tag_gossip_links

  validates :title,
  presence: true,
  uniqueness: true
end

app/models/tag_gossip_link.rb
class TagGossipLink < ApplicationRecord
  belongs_to :gossip
  belongs_to :tag
end

app/models/user.rb
class User < ApplicationRecord

  has_secure_password

  belongs_to :city
  has_many :gossips
  has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
  has_many :recipient_to_pm_links, foreign_key: 'recipient_id'
  has_many :received_messages, foreign_key: 'received_message_id', class_name: "PrivateMessage", through: :recipient_to_pm_links
  has_many :likes
  
  validates :email,
  presence: true,
  uniqueness: true,
  format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "Mauvais format" }

  validates :password,
  presence: true,
  length: { in: 6..20 }

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  def show
  end

  def new
      @like = Like.new
  end

  def create
      @like = Like.create(user_id: current_user.id , gossip_id: params[:gossip_id])
      redirect_back(fallback_location: root_path)
  end

  def destroy
      @like = Like.find(params[:id])
      like_user = @like.user

      if current_user == like_user
          @like.destroy
          redirect_back(fallback_location: root_path)
      else
      end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/gossips_helper.rb
module GossipsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def current_user
    User.find_by(id: session[:user_id])
  end

   def log_in(user)
    session[:user_id] = user.id
  end

  def logged_in?
    if session[:user_id] !=nil
      return true
    else
      return false
    end
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/team_helper.rb
module TeamHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheGossipProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <%= link_to "THE GOSSIP PROJECT", root_path, class:"navbar-brand text-primary" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "La Team", team_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Contact", contact_path, class:"nav-link" %>
        </li>
      </ul>
    </div>

    <%= link_to "Créer un potin", new_gossip_path, class:"btn btn-warning", role:"button" %>

    <% if logged_in? == true%>
      <div class="btn-group">
      <button type="button" class="btn btn-outline-info btn-sm">Bienvenue <%= current_user.first_name %> 🔥</button>
      <button type="button" class="btn btn-info dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <span class="sr-only">Toggle Dropdown</span>
      </button>
      <div class="dropdown-menu">
        <%= link_to "Ton profil", user_path(id: current_user.id), class:"dropdown-item" %>
        <div class="dropdown-divider"></div>
        <%= link_to "Déconnexion", session_path(session.id), method: :delete, class:"dropdown-item" %>
      </div>
      </div>
      <% else %>
      <%= link_to "Inscription", new_user_path, class:"btn btn-outline-info btn-sm", role:"button" %>
      <%= link_to "Connexion", new_session_path, class:"btn btn-info btn-sm", role:"button" %>
    <% end %>


  </nav>

  <body>

    <% if flash[:danger] %>
      <div class="alert alert-danger" role="alert">
        <%= flash[:danger] %>
      </div>
    <% end %>

    <% if flash[:success] %>
      <div class="alert alert-success" role="alert">
        <%= flash[:success] %>
      </div>
    <% end %>

    <%= yield %>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>